[package]
authors = [
    "Richard Diamond <wichard@vitalitystudios.com>",
    "Kornel LesinÌski <kornel@geekhood.net>",
]
build = "build.rs"
description = "Rust FFI bindings and wrapper for libwebm"
license = "MPL-2.0"
name = "webm-sys-native"
repository = "https://github.com/pornel/rust-webm.git"
version = "0.3.0"

[build-dependencies]
gcc = "0.3.42"

[dependencies]
libc = "0.2.20"

[lib]
name = "webm_sys"
path = "lib.rs"
